swagger: '2.0'
host: '127.0.0.1:8080'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag

paths:
  /bottle/auth/login:
    post:
      summary: User login
      parameters:
        - name: login
          in: json
          required: True
          description: User login
        - name: password
          in: json
          required: True
          description: User password
      produces:
        - application/text
      responses:
        '200':
          description: OK
          schema:
            example: |
              {
              status: "success",
              text: "User user_login: logged in"
              }
