swagger: '2.0'
info:
  title: Swagger for Bottle
  description: Sample config for swagger in a Bottle
host: '127.0.0.1:8080'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag
  - name: getmethods
    description: tag for GET methods
  - name: postmethods
    description: tag for POST methods

paths:
  /index:
    get:
      tags: default
      summary: Yet Another Index
      produces:
        - application/text
      responses:
        '200':
          description: OK
          schema:
            example: "Bulk Page"
      tags:
        - default
  /bottle/auth/login:
    get:
      tags:
        - getmethods
      summary: User login to server
      description: ''
      parameters:
        - name: login
          in: query
          description: User login name
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: User password
          required: true
          schema:
            type: string




#   /bottle/auth/login:
#     post:
#       summary: User login
#       requestBody:
#         required: true
#         content:
#           application/json:
#             schema:
#               type: object
#               properties:
#                 login:
#                   type: string
#                 password:
#                   type: string
#       responses:
#         '200':
#           description: User login result
#           content:
#             application/json
#               schema:
#                 type: object
#                 properties:
#                   status:
#                     type: string
#                     example: success
#                   text:
#                     type: string
#                     example: User login logged in
#         default:
#           description: Unexpected error
