swagger: '2.0'
host: '127.0.0.1:8080'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag

paths:
  /bottle/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User login result
          content:
            application/json
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  text:
                    type: string
                    example: User login logged in
        default:
          description: Unexpected error
